### ISSUE TITLE
GOLEM Paper Checklist

### ISSUE THREAD

**Issue by gkirgizov** [aimclub/GOLEM#126]
This is the meta-issue tracking progress with GOLEM paper that introduces GOLEM framework with use-cases and adaptive features.
Paper Focus:
- Modular approach (specification of anything), incl. Verification Rules; 
- Bandits: adaptability per each domain (universal set of mutations; bandits that adapt them)
- ReproductionController -- controls population & compensates for mistakes in real use cases

Pre-requisite PRs & Issues:
- [ ] #101 
- [ ] #104 
- [ ] #124 
- [ ] Optionally, but desirably: #115 

Experiments:
- [ ] Comparable performance on some tasks with DEAP / pymoo
- [ ] (Optional) ReproductionController in Noisy domains -- showing that this feature helps
- [ ] Adaptive mutations -- no need to expertly fine-tune it per task in question.
    - [ ] simple bandits proof-of-concept -- pruning unneeded mutations
    - [ ] simple bandits proof-of-concept -- mutations with dynamic probabilities
    - [ ] simple bandits real case -- molecule search
    - [ ] contextual bandits with simple graph features -- molecule search

What's required from collaborators who will describe their use cases:
- [ ] Run GOLEM with Adaptive Mutations, see if it helps
