### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by maypink** [aimclub/GOLEM#220]
Tasks to do:

- [x] Bug fix with disabling history #216
- [x] Bug fix with serialization #215  
- [x] Mutations probabilities research and fix #205 -- probably will not be included in 0.4.0 release, since this research was united with parallelization of genetic operators in GOLEM.
- [x] Light-weighted histories #118
