### ISSUE TITLE
Release 0.4.1

### ISSUE THREAD

**Issue by maypink** [aimclub/GOLEM#254]
PRs to include in release:

- [x] GOLEM API (#251)
- [x] Custom selection (#249)
- [ ] Sequential Tuner Fix (#248)
- [ ] Set random seed for Integration Tests (#217)
- [ ] Parallel Optimizer (#247) :game_die:
- [ ] Minor fixes for BAMT (#169)
- [x] Mutation Operator Fix (#238)
- [ ] Crossover for graph with cycles (#231)
